---
jobs:
- name: fetch-opsman
  plan:
  - in_parallel: 
    - get: configuration
    - get: platform-automation-tasks
      params: { unpack: true }
    - get: platform-automation-image
      params: { unpack: true }
    - get: daily
      trigger: true

  - task: interpolate-env-creds
    image: platform-automation-image
    file: platform-automation-tasks/tasks/credhub-interpolate.yml
    params:
      CREDHUB_CLIENT: ((credhub-client))
      CREDHUB_SECRET: ((credhub-secret))
      CREDHUB_SERVER: ((credhub-server))
      CREDHUB_CA_CERT: ((credhub-ca-cert.certificate))
      PREFIX: '/concourse/main'
      INTERPOLATION_PATHS: download-product
      SKIP_MISSING: false
    input_mapping:
      files: configuration
    output_mapping:
      interpolated-files: interpolated-configs

  - task: download-opsman-product
    image: platform-automation-image
    file: platform-automation-tasks/tasks/download-product.yml
    params: 
      CONFIG_FILE: download-product/opsman.yml
    input_mapping:
      config: interpolated-configs

  - put: opsman-product
    params:
      file: downloaded-product/*

resources:
  - name: platform-automation-tasks
    type: gcs
    source:
      bucket: ((bucket))
      regexp: platform-automation-tasks-(.+).zip
      json_key: ((json_key))
  - name: platform-automation-image
    type: gcs
    source:
      bucket: ((bucket))
      regexp: platform-automation-image-(.+).tgz
      json_key: ((json_key))
  - name: opsman-product
    type: gcs
    source:
      bucket: ((bucket))
      regexp: \[ops-manager,(.*)].*.yml
      json_key: ((json_key))
  - name: configuration
    type: git
    source:
      private_key: ((config-repo-key.private_key))
      uri: ((config-repo-uri))
  - name: daily
    type: time
    source:
      interval: 24h

resource_types:
  - name: gcs
    type: docker-image
    source:
      repository: frodenas/gcs-resource

