---
jobs:
- name: test-job
  plan:
  - in_parallel: 
    - get: platform-automation-tasks
      params: { unpack: true }
    - get: platform-automation-image
      params: { unpack: true }
  - task: test
    file: platform-automation-tasks/tasks/test.yml
    image: platform-automation-image
resources:
  - name: platform-automation-tasks
    type: gcs
    source:
      bucket: ((bucket))
      regexp: platform-automation-tasks-(.+).zip
      json_key: ((json_key))
  - name: platform-automation-image
    type: gcs
    source:
      bucket: ((bucket))
      regexp: platform-automation-image-(.+).tgz
      json_key: ((json_key))
resource_types:
  - name: gcs
    type: docker-image
    source:
      repository: frodenas/gcs-resource

